PlacementManagement/Controllers/PlacementstatusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PlacementManagement.Models;

namespace PlacementManagement.Controllers
{
    public class PlacementstatusesController : Controller
    {
        private DBPlacements db = new DBPlacements();

        // GET: Placementstatuses
        public ActionResult Index(string searchCompany,string searchStudent, string sort)
        {
            
            var placementstatus1 = db.Placementstatus.Include(p => p.company).Include(p => p.student);
            var placementstatus = placementstatus1;
            
            
                if (Session["role"].ToString().Equals("Student"))
                {
                    string name = Session["uname"].ToString();
                    placementstatus1 = placementstatus.Where(s => s.student.Name.Equals(name));
                }
                else if (Session["role"].ToString().Equals("Admin"))
                {
                    string dept = Session["dept"].ToString();
                    placementstatus1 = placementstatus.Where(s => s.student.Dept.deptName.Equals(dept));
                }
                else
                    return Redirect("/Students/Login");
                ViewBag.StatusSort = sort == "ascs" ? "dscs" : "ascs";
                ViewBag.CompanySort = sort == "ascc" ? "dscc" : "ascc";
                if (!string.IsNullOrEmpty(searchCompany))
                {
                    placementstatus1 = placementstatus1.Where(ps => ps.company.companyName.Contains(searchCompany));
                }
                if (!string.IsNullOrEmpty(searchStudent))
                {
                    placementstatus1 = placementstatus1.Where(ps => ps.student.Name.Contains(searchStudent));
                }
                switch (sort)
                {
                    case "ascc":
                        placementstatus1 = placementstatus1.OrderBy(ps => ps.company.companyName);
                        break;
                    case "dscc":
                        placementstatus1 = placementstatus1.OrderByDescending(ps => ps.company.companyName);
                        break;
                    case "ascs":
                        placementstatus1 = placementstatus1.OrderBy(ps => ps.Status);
                        break;
                    case "dscs":
                        placementstatus1 = placementstatus1.OrderByDescending(ps => ps.Status);
                        break;
                }
                placementstatus = placementstatus1;
                ViewBag.plac = placementstatus.ToList();
                return View();
            /*
            catch (Exception e)
            {
                Console.Write(e);
                //ViewData["plac"] = placementstatus.ToList();
                return View();
            }*/
        }

        // GET: Placementstatuses/Details/5
        public ActionResult Details(int companyId, int studentId)
        {
            if (!Session["role"].ToString().Equals("Admin"))
                return Redirect("/Students/Login");
            Placementstatus placementstatus = db.Placementstatus.Find(companyId, studentId);
            if (placementstatus == null)
            {
                return HttpNotFound();
            }
            return View(placementstatus);
        }

        // GET: Placementstatuses/Create
        public ActionResult Create()
        {
            try
            {
                if (Session["role"].ToString().Equals("Admin"))
                {
                    string dept = Session["dept"].ToString();
                    var students = db.Students.Where(s => s.Dept.deptName.Equals(dept));
                    ViewBag.companyId = new SelectList(db.Companies, "companyId", "companyName");
                    ViewBag.studentId = new SelectList(students, "studentId", "Name");
                    return View();
                }
                else
                    return Redirect("/Students/Login");
            }
            catch(Exception e)
            {
                Console.Write(e);
                return Redirect("/Students/Login");
            }
        }

        // POST: Placementstatuses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "companyId,studentId,Status")] Placementstatus placementstatus)
        {
            if (ModelState.IsValid)
            {
                db.Placementstatus.Add(placementstatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.companyId = new SelectList(db.Companies, "companyId", "companyName", placementstatus.companyId);
            ViewBag.studentId = new SelectList(db.Students, "studentId", "Name", placementstatus.studentId);
            return View(placementstatus);
        }

        // GET: Placementstatuses/Edit/5
        public ActionResult Edit(int companyId, int studentId)
        {
            if (!Session["role"].ToString().Equals("Admin"))
                return Redirect("/Students/Login");
            Placementstatus placementstatus = db.Placementstatus.Find(companyId, studentId);
            if (placementstatus == null)
            {
                return HttpNotFound();
            }
            var students = db.Students.Where(s => s.Dept.deptName.Equals(Session["dept"].ToString()));
            ViewBag.companyId = new SelectList(db.Companies, "companyId", "companyName", placementstatus.companyId);
            ViewBag.studentId = new SelectList(students, "studentId", "Name", placementstatus.studentId);
            return View(placementstatus);
        }

        // POST: Placementstatuses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "companyId,studentId,Status")] Placementstatus placementstatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(placementstatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.companyId = new SelectList(db.Companies, "companyId", "companyName", placementstatus.companyId);
            ViewBag.studentId = new SelectList(db.Students, "studentId", "Name", placementstatus.studentId);
            return View(placementstatus);
        }

        // GET: Placementstatuses/Delete/5
        public ActionResult Delete(int companyId, int studentId)
        {
            if (!Session["role"].ToString().Equals("Admin"))
                return Redirect("/Students/Login");
            Placementstatus placementstatus = db.Placementstatus.Find(companyId, studentId);
            if (placementstatus == null)
            {
                return HttpNotFound();
            }
            return View(placementstatus);
        }

        // POST: Placementstatuses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int companyId, int studentId)
        {
            Placementstatus placementstatus = db.Placementstatus.Find(companyId, studentId);
            db.Placementstatus.Remove(placementstatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PlacementManagement/Views/Placementstatuses/Create.cshtml
@model PlacementManagement.Models.Placementstatus

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Placementstatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.companyId, "companyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("companyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.companyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.studentId, "studentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("studentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.studentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Status, "In Process") In Process
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PlacementManagement/Views/Placementstatuses/Delete.cshtml
@model PlacementManagement.Models.Placementstatus

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Placementstatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.company.companyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company.companyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PlacementManagement/Views/Placementstatuses/Details.cshtml
@model PlacementManagement.Models.Placementstatus

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Placementstatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.company.companyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company.companyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PlacementManagement/Views/Placementstatuses/Edit.cshtml
@model PlacementManagement.Models.Placementstatus

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Placementstatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.companyId)

        @Html.HiddenFor(model => model.studentId)

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Status, "In Process") In Process
                @Html.RadioButtonFor(model => model.Status, "Accepted") Accepted
                @Html.RadioButtonFor(model => model.Status, "Rejected") Rejected
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PlacementManagement/Views/Placementstatuses/Index.cshtml
@model PlacementManagement.Models.Placementstatus

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (Session["role"].ToString().Equals("Admin"))
{
<p>
    @Html.ActionLink("Create New", "Create")
</p>
}
@using (Html.BeginForm("Index", "Placementstatuses", FormMethod.Post))
{
    <div>
        Search by Company Name:@Html.TextBox("searchCompany")
        <input id="Submit1" type="submit" value="Search" />
    </div>
    if (Session["role"].ToString().Equals("Admin"))
    {

    <div>
        Search by Student Name:@Html.TextBox("searchStudent")
        <input id="Submit1" type="submit" value="Search" />
    </div>
    }
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Company", "Index", new { sort = ViewBag.CompanySort })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.student.Name)
        </th>
        <th>
            @Html.ActionLink("Status","Index",new { sort = ViewBag.StatusSort })
        </th>
        <th></th>
    </tr>

@if (ViewBag.plac != null)
{
    foreach (var p in ViewData["plac"] as IList<PlacementManagement.Models.Placementstatus>)
    {
        <tr>
            <td>
                @p.company.companyName
            </td>
            <td>
                @p.student.Name
            </td>
            <td>
                @p.Status
            </td>
           @if (Session["role"].ToString().Equals("Admin"))
           {
            <td>
                @Html.ActionLink("Edit", "Edit", new { companyId = p.companyId, studentId = p.studentId }) |
                @Html.ActionLink("Details", "Details", new { companyId = p.companyId, studentId = p.studentId }) |
                @Html.ActionLink("Delete", "Delete", new { companyId = p.companyId, studentId = p.studentId })
            </td>
           }
        </tr>
    }
}
</table>